name: Terraform

on: push

env:
  TF_LOG: INFO
  TF_INPUT: false

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./network_config   # ✅ FIXED

    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.7

      # Debug (now shows correct folder)
      - name: Show files
        run: |
          pwd
          ls -la

      # Init
      - name: Terraform Init
        run: terraform init

      # Format check
      - name: Terraform Format
        run: terraform fmt -check

      # Validate
      - name: Terraform Validate
        if: always()
        run: terraform validate