name: 'Terraform'

on: push

env:
  TF_LOG: INFO
  TF_INPUT: false

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Setup Terraform Cloud credentials
      run: |
        mkdir -p ~/.terraform.d
        cat > ~/.terraform.d/credentials.tfrc.json <<EOF
        {
          "credentials": {
            "app.terraform.io": {
              "token": "${{ secrets.TF_API_TOKEN }}"
            }
          }
        }
        EOF

    - name: Terraform Init
      id: init
      run: terraform init -input=false

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check

    - name: Terraform Validate
      id: validate
      if: ${{ success() || failure() }}
      run: |
        terraform init -input=false
        terraform validate